"""Initial schema

Revision ID: 05f15b2b6e0e
Revises: 
Create Date: 2026-08-22 15:07:56.517388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f15b2b6e0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False, comment='E.g. COLLECTOR_STATE_CHANGED, INCIDENT_CREATED, HEAL_APPROVED, RUN_COMPLETED'),
    sa.Column('related_entity_ref', sa.String(length=255), nullable=False, comment="Reference like 'collector:1', 'incident:3', 'run:12'"),
    sa.Column('actor_source', sa.String(length=128), nullable=False, comment="Who/what triggered the event: 'system', 'operator', 'bright_data'"),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('collectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bright_data_collector_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('current_contract_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('HEALTHY', 'DEGRADED', 'DRIFT_DETECTED', 'DIAGNOSING', 'HEAL_PROPOSED', 'AWAITING_APPROVAL', 'APPROVED', 'HEALING', 'VERIFYING', 'RECOVERED', 'REJECTED', 'VERIFICATION_FAILED', 'HEAL_FAILED', 'MANUAL_INTERVENTION', name='collectorstate'), nullable=False),
    sa.Column('latest_health_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collectors_bright_data_collector_id'), 'collectors', ['bright_data_collector_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.Enum('COLLECTION', 'HEAL_REQUEST', 'HEAL_APPROVE', 'VERIFICATION', name='joboperationtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('related_entity_ref', sa.String(length=255), nullable=True, comment="Reference to the related entity, e.g. 'collector:1' or 'incident:5'"),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('data_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', name='contractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_collector_id'), 'runs', ['collector_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('trigger_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRIFT_DETECTED', 'DIAGNOSING', 'HEAL_PROPOSED', 'AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'HEALING', 'VERIFYING', 'RECOVERED', 'VERIFICATION_FAILED', 'HEAL_FAILED', 'MANUAL_INTERVENTION', name='incidentstatus'), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.ForeignKeyConstraint(['trigger_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_collector_id'), 'incidents', ['collector_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bright_data_snapshot_id', sa.String(length=128), nullable=False, comment='Bright Data execution result identifier (j_xxxxx). Unique constraint prevents duplicate snapshots.'),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('validation_state', sa.Enum('PENDING', 'VALID', 'INVALID', 'DEGRADED', 'DRIFT_DETECTED', name='validationstate'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('schema_validity_score', sa.Float(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('validation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_bright_data_snapshot_id'), 'snapshots', ['bright_data_snapshot_id'], unique=True)
    op.create_index(op.f('ix_snapshots_collector_id'), 'snapshots', ['collector_id'], unique=False)
    op.create_index(op.f('ix_snapshots_run_id'), 'snapshots', ['run_id'], unique=False)
    op.create_table('healing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'HEALING', 'VERIFYING', 'RECOVERED', 'FAILED', name='healingstatus'), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('verification_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['verification_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healing_events_incident_id'), 'healing_events', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healing_events_incident_id'), table_name='healing_events')
    op.drop_table('healing_events')
    op.drop_index(op.f('ix_snapshots_run_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_collector_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_bright_data_snapshot_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_collector_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_collector_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('data_contracts')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_collectors_bright_data_collector_id'), table_name='collectors')
    op.drop_table('collectors')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
