"""Phase 2 cleanup

Revision ID: f11d6dd45df1
Revises: 05f15b2b6e0e
Create Date: 2026-08-22 15:17:57.279086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11d6dd45df1'
down_revision: Union[str, Sequence[str], None] = '05f15b2b6e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collectors', 'target_url')
    op.drop_column('collectors', 'name')
    op.create_index('ix_active_healing_event_per_incident', 'healing_events', ['incident_id'], unique=True, sqlite_where=sa.text("status NOT IN ('RECOVERED', 'REJECTED', 'FAILED')"), postgresql_where=sa.text("status NOT IN ('RECOVERED', 'REJECTED', 'FAILED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_active_healing_event_per_incident', table_name='healing_events', sqlite_where=sa.text("status NOT IN ('RECOVERED', 'REJECTED', 'FAILED')"), postgresql_where=sa.text("status NOT IN ('RECOVERED', 'REJECTED', 'FAILED')"))
    op.add_column('collectors', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('collectors', sa.Column('target_url', sa.VARCHAR(length=2048), nullable=False))
    # ### end Alembic commands ###
